import type { CarListing, AuctionListing, User } from '@/types';
import { generateId } from './storage';

const CAR_IMAGES = [
  'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80',
  'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80',
  'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80',
  'https://images.unsplash.com/photo-1571607388263-1044f9ea01dd?w=800&q=80',
  'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80',
  'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&q=80',
  'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80',
  'https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=800&q=80',
];

export const SEED_USERS: User[] = [
  {
    id: 'user-001',
    name: 'James Whitmore',
    email: 'james@vccp.com',
    password: 'password123',
    role: 'both',
    createdAt: Date.now() - 86400000 * 30,
  },
  {
    id: 'user-002',
    name: 'Eleanor Voss',
    email: 'eleanor@vccp.com',
    password: 'password123',
    role: 'seller',
    createdAt: Date.now() - 86400000 * 20,
  },
  {
    id: 'user-003',
    name: 'Harold Banks',
    email: 'harold@vccp.com',
    password: 'password123',
    role: 'bidder',
    createdAt: Date.now() - 86400000 * 10,
  },
];

export const SEED_LISTINGS: CarListing[] = [
  {
    id: 'car-001',
    title: '1967 Ford Mustang Fastback',
    make: 'Ford',
    model: 'Mustang',
    year: 1967,
    price: 85000,
    mileage: 72000,
    condition: 'Excellent',
    transmission: 'Manual',
    fuelType: 'Petrol',
    bodyStyle: 'Coupe',
    driveType: 'RWD',
    engineSize: '4.7L V8',
    color: 'Highland Green',
    interiorColor: 'Black',
    doors: 2,
    vin: '7T02S123456',
    description: 'Stunning 1967 Mustang Fastback in rare Highland Green. Numbers-matching engine, fully restored to factory specifications. This is a true collector\'s piece.',
    features: ['Power Steering', 'Rally Pack Gauges', 'Pony Interior', 'Air Conditioning', 'AM/FM Radio'],
    images: [CAR_IMAGES[0], CAR_IMAGES[1]],
    location: 'Detroit, MI',
    sellerName: 'James Whitmore',
    sellerPhone: '(313) 555-0101',
    sellerEmail: 'james@vccp.com',
    status: 'active',
    createdAt: Date.now() - 86400000 * 5,
    viewCount: 234,
  },
  {
    id: 'car-002',
    title: '1969 Chevrolet Camaro Z/28',
    make: 'Chevrolet',
    model: 'Camaro',
    year: 1969,
    price: 95000,
    mileage: 58000,
    condition: 'Very Good',
    transmission: 'Manual',
    fuelType: 'Petrol',
    bodyStyle: 'Coupe',
    driveType: 'RWD',
    engineSize: '5.0L V8',
    color: 'Fathom Green',
    interiorColor: 'Black',
    doors: 2,
    vin: '9N578S123456',
    description: 'Rare 1969 Camaro Z/28 with documentation. DZ 302 engine, Muncie 4-speed. Matching numbers car in exceptional condition.',
    features: ['4-Speed Muncie', 'Front Disc Brakes', 'Rally Wheels', 'Positraction', 'Headers'],
    images: [CAR_IMAGES[2], CAR_IMAGES[3]],
    location: 'Chicago, IL',
    sellerName: 'Eleanor Voss',
    sellerPhone: '(312) 555-0202',
    sellerEmail: 'eleanor@vccp.com',
    status: 'active',
    createdAt: Date.now() - 86400000 * 8,
    viewCount: 189,
  },
  {
    id: 'car-003',
    title: '1957 Chevrolet Bel Air',
    make: 'Chevrolet',
    model: 'Bel Air',
    year: 1957,
    price: 72000,
    mileage: 85000,
    condition: 'Excellent',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyStyle: 'Sedan',
    driveType: 'RWD',
    engineSize: '4.6L V8',
    color: 'India Ivory / Onyx Black',
    interiorColor: 'Red & White',
    doors: 4,
    vin: '57B123456',
    description: 'Iconic two-tone 1957 Bel Air. Powerglide automatic, fuel injection option. Showroom condition, won multiple concours awards.',
    features: ['Fuel Injection', 'Power Windows', 'Power Brakes', 'Continental Kit', 'Chrome Package'],
    images: [CAR_IMAGES[4], CAR_IMAGES[5]],
    location: 'Nashville, TN',
    sellerName: 'James Whitmore',
    sellerPhone: '(615) 555-0303',
    sellerEmail: 'james@vccp.com',
    status: 'active',
    createdAt: Date.now() - 86400000 * 3,
    viewCount: 312,
  },
  {
    id: 'car-004',
    title: '1970 Plymouth Barracuda',
    make: 'Plymouth',
    model: 'Barracuda',
    year: 1970,
    price: 145000,
    mileage: 42000,
    condition: 'Excellent',
    transmission: 'Manual',
    fuelType: 'Petrol',
    bodyStyle: 'Coupe',
    driveType: 'RWD',
    engineSize: '7.0L V8 Hemi',
    color: 'Plum Crazy Purple',
    interiorColor: 'Black',
    doors: 2,
    vin: 'BS23V0A100001',
    description: 'Ultra-rare 440 Six Pack Barracuda in stunning Plum Crazy Purple. One of the most sought-after muscle cars. Documentation and broadcast sheet included.',
    features: ['440 Six Pack', 'Dana 60 Rear', 'Manual 4-Speed', 'Power Steering', 'Air Grabber Hood'],
    images: [CAR_IMAGES[6], CAR_IMAGES[7]],
    location: 'Los Angeles, CA',
    sellerName: 'Eleanor Voss',
    sellerPhone: '(213) 555-0404',
    sellerEmail: 'eleanor@vccp.com',
    status: 'active',
    createdAt: Date.now() - 86400000 * 12,
    viewCount: 521,
  },
  {
    id: 'car-005',
    title: '1965 Shelby Cobra 427',
    make: 'Shelby',
    model: 'Cobra',
    year: 1965,
    price: 280000,
    mileage: 18000,
    condition: 'Excellent',
    transmission: 'Manual',
    fuelType: 'Petrol',
    bodyStyle: 'Roadster',
    driveType: 'RWD',
    engineSize: '7.0L V8',
    color: 'Guardsman Blue',
    interiorColor: 'Black Leather',
    doors: 2,
    vin: 'CSX3001',
    description: 'Authentic Shelby Cobra 427 with Shelby American documentation. Side-oiler FE engine producing over 480 horsepower. Investment-grade example.',
    features: ['427 Side-Oiler', 'Roll Bar', 'Tonneau Cover', 'Side Pipes', 'Original Hardtop'],
    images: [CAR_IMAGES[1], CAR_IMAGES[3]],
    location: 'Scottsdale, AZ',
    sellerName: 'James Whitmore',
    sellerPhone: '(480) 555-0505',
    sellerEmail: 'james@vccp.com',
    status: 'active',
    createdAt: Date.now() - 86400000 * 2,
    viewCount: 892,
  },
  {
    id: 'car-006',
    title: '1971 Dodge Charger R/T',
    make: 'Dodge',
    model: 'Charger',
    year: 1971,
    price: 68000,
    mileage: 94000,
    condition: 'Very Good',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyStyle: 'Coupe',
    driveType: 'RWD',
    engineSize: '6.3L V8',
    color: 'Hemi Orange',
    interiorColor: 'Black',
    doors: 2,
    vin: 'WS23G1A100001',
    description: 'Last of the B-body Chargers in classic Hemi Orange. 440 Magnum engine with 3-speed automatic. Restored and documented.',
    features: ['440 Magnum', 'TorqueFlite Automatic', 'Rallye Wheels', 'Dual Exhaust', 'Bucket Seats'],
    images: [CAR_IMAGES[5], CAR_IMAGES[7]],
    location: 'Atlanta, GA',
    sellerName: 'Eleanor Voss',
    sellerPhone: '(404) 555-0606',
    sellerEmail: 'eleanor@vccp.com',
    status: 'active',
    createdAt: Date.now() - 86400000 * 7,
    viewCount: 167,
  },
];

export function createSeedAuctions(listings: CarListing[]): AuctionListing[] {
  const now = Date.now();
  const car1 = listings.find(c => c.id === 'car-001');
  const car4 = listings.find(c => c.id === 'car-004');
  const car5 = listings.find(c => c.id === 'car-005');

  const auctions: AuctionListing[] = [];

  if (car1) {
    auctions.push({
      id: generateId(),
      carId: car1.id,
      car: car1,
      sellerId: 'user-001',
      sellerName: 'James Whitmore',
      reservePrice: 80000,
      startingBid: 60000,
      currentBid: 67500,
      currentBidderId: 'user-003',
      currentBidderName: 'Harold Banks',
      bids: [
        { id: generateId(), auctionId: '', bidderId: 'user-003', bidderName: 'Harold Banks', amount: 62000, timestamp: now - 3600000 },
        { id: generateId(), auctionId: '', bidderId: 'user-003', bidderName: 'Harold Banks', amount: 65000, timestamp: now - 1800000 },
        { id: generateId(), auctionId: '', bidderId: 'user-003', bidderName: 'Harold Banks', amount: 67500, timestamp: now - 900000 },
      ],
      status: 'live',
      durationHours: 24,
      startTime: now - 3600000 * 6,
      endTime: now + 3600000 * 18,
      createdAt: now - 86400000,
    });
  }

  if (car4) {
    auctions.push({
      id: generateId(),
      carId: car4.id,
      car: car4,
      sellerId: 'user-002',
      sellerName: 'Eleanor Voss',
      reservePrice: 130000,
      startingBid: 100000,
      currentBid: 118000,
      currentBidderId: 'user-001',
      currentBidderName: 'James Whitmore',
      bids: [
        { id: generateId(), auctionId: '', bidderId: 'user-001', bidderName: 'James Whitmore', amount: 105000, timestamp: now - 7200000 },
        { id: generateId(), auctionId: '', bidderId: 'user-001', bidderName: 'James Whitmore', amount: 112000, timestamp: now - 3600000 },
        { id: generateId(), auctionId: '', bidderId: 'user-001', bidderName: 'James Whitmore', amount: 118000, timestamp: now - 1200000 },
      ],
      status: 'live',
      durationHours: 48,
      startTime: now - 3600000 * 12,
      endTime: now + 3600000 * 36,
      createdAt: now - 86400000 * 2,
    });
  }

  if (car5) {
    auctions.push({
      id: generateId(),
      carId: car5.id,
      car: car5,
      sellerId: 'user-001',
      sellerName: 'James Whitmore',
      reservePrice: 250000,
      startingBid: 200000,
      currentBid: 200000,
      currentBidderId: '',
      currentBidderName: '',
      bids: [],
      status: 'upcoming',
      durationHours: 72,
      startTime: now + 3600000 * 6,
      endTime: now + 3600000 * 78,
      createdAt: now - 3600000,
    });
  }

  return auctions;
}
